name: E2E test with allure-report
'on':
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Download Cypress
              uses: bahmutov/npm-install@v1
              env:
                  CYPRESS_INSTALL_BINARY: 0

            - name: Check Cypress cache
              run: |
                  npx cypress cache path
                  npx cypress cache list

            - name: restore / cache the binary
              id: cache-cypress
              uses: actions/cache@v1
              with:
                  path: ~/.cache/Cypress
                  key: >-
                      cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package.json')
                      }}

            - name: Install Cypress
              run: |
                  npx cypress install
                  npx cypress cache list

            - name: Run Cypress
              continue-on-error: true
            - name: Install cypress-cucumber-preprocessor
              run: npm install @badeball/cypress-cucumber-preprocessor
            - name: Install cypress-esbuild-preprocessor
              run: npm i --seve-dev @bahmutov/cypress-esbuild-preprocessor
            - name: Install reporter dev
              run: npm install multiple-cucumber-html-reporter --save-dev
              run: npm run cy:test
              
            - name: Generate reports
              if: always()
              run: npm run cypress:report
            - name: Upload artifact cucumber-report
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: cucumber-report
                  path: ./reports/cucumber-htmlreport 
            - name: Deploy to pages
              if: always()
              uses: peaceiris/actions-gh-pages@v3.8.0
              with:
                  github_token: ${{ secrets.ACCESS_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: reports/cucumber-htmlreport/ 