name: BDD test with cypress-cucumber
on:
    workflow_dispatch:
    push:
        branches: [main]
jobs:
    Run_test:
        runs-on: windows-latest
        strategy:
            matrix:
                node-version: [16.17.0]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: update node manager
              run: npm i npm@latest
            - name: install all dependencies
              run: npm i
            - name: Install Cypress
              run: npm install cypress
            - name: Install cypress-cucumber-preprocessor
              run: npm install @badeball/cypress-cucumber-preprocessor
            - name: Install cypress-esbuild-preprocessor
              run: npm i --seve-dev @bahmutov/cypress-esbuild-preprocessor
            - name: Install reporter dev
              run: npm install multiple-cucumber-html-reporter --save-dev
            - name: run test
              run: npm run cypress:run
            - name: Generate reports
              if: always()
              run: npm run cypress:report
            - name: Upload artifact cucumber-report
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: cucumber-report
                  path: reports/cucumber-htmlreport 
            - name: Deploy to pages
              if: always()
              uses: peaceiris/actions-gh-pages@v3.8.0
              with:
                  github_token: ${{ secrets.ACCESS_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: reports/cucumber-htmlreport/ 